import {  Roboto} from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";


const myFont1 = Roboto( {
  subsets : ["latin"],
  weight : ["400" , "900"],
}) 

export const metadata: Metadata = {
  title: "Create Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont1.className} antialiased`}
      ><Header/>
        {children}
        <Footer/>
      </body >
    </html>
  );
}

